[build]
  publish = "frontend"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
